name: TPA
version: '${project.version}'
main: top.craft_hello.tpa.TPA
api-version: '1.20'
author: WarSkyGod
folia-supported: true

commands:
  tpa:
  tphere:
  tpaccept:
  tpdeny:
  restp:
  restpset:
    permission: tpa.restpset
    permission-message:  '&a&l> &c&l你没有权限使用这个命令！'